version: "3.1"

services:
  mssql:
      image: 'mcr.microsoft.com/mssql/server'
      ports:
          - '1433:1433'
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Secret1234
      volumes:
          - '.:/var/opt/mssql'